#!/system/bin/sh
#
# Compcache handler
# Decides whether or not Compcache is enabled
#
MEMTOTAL=$( awk '{ if ($1 eq "MemTotal:") print $2 ;exit }' </proc/meminfo )

if [ `getprop persist.service.compcache` == 1 ];
then
  PROP=`getprop ro.compcache.default`
  setprop persist.service.compcache $PROP
fi

if [ -e /data/property/persist.service.compcache ];
then
  PROP=`getprop persist.service.compcache`
else
  PROP=`getprop ro.compcache.default`
  setprop persist.service.compcache $PROP
fi

if [ $PROP != 0 ]
then
  CCSIZE=$(($(($MEMTOTAL * $PROP)) / 100))
  /system/bin/compcache start $CCSIZE
else
  /system/bin/compcache stop
fi

exit 0

